name: Create tag

on:
  push:
    branches:
      - master
jobs:
  create_tag:
    runs-on: ubuntu-latest
    if: "! contains(github.actor, 'pirate-bot')"
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Build files using ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Create tag
        run: |
          npm ci
          git config --global user.email "marius+gitbot@themeisle.com"
          git config --global user.name "themeisle[bot]"
          npm version patch -m "[skip ci] New version %s"
          git push "https://${{ github.actor }}:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:master --follow-tags
        env:
          CI: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  empty-job:
    # if no jobs run, github action considers it a test failure -- which seems like a bug
    # this makes it so the top-level if statement for the job does not give status failure.
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Meep
        run: |
          echo "Nothing to do"